### ISSUE TITLE
Add cross build for Scala 2.13

### ISSUE THREAD

**Issue by bijancn** [47degrees/fetch#216]
I might to be blind to find it but I don't see any progress or discussion towards adding Scala 2.13 (and sbt 1.3 ?) to the build. As I am currently upgrading my services, this is the first library that doesn't have a 2.13 release. The upgrade itself should not be hard to do.

That being said I would also like to see cats effect 2.0 being used. Should I put this to a separate issue?

**Comment by purrgrammer** [comment]
> I might to be blind to find it but I don't see any progress  or discussion towards adding Scala 2.13 (and sbt 1.3 ?) to the build.  As I am currently upgrading my services, this is the first library that  doesn't have a 2.13 release. The upgrade itself should not be hard to  do.

Indeed, upgrading to Scala 2.13 should be straightforward, I think we can probably support 2.11 through 2.13, although I'm fine dropping support for the 2.11 series. I'll leave this issue open to address it, happy to review/merge a PR if you have the time. If not I'll get to it at some point.


> That being said I would also like to see cats effect 2.0 being used. Should I put this to a separate issue?

The latest release (1.2.0) is using cats-effect 2.0, so there is no need for another issue. Thanks for reporting!

**Comment by bijancn** [comment]
Cool! When you don't have too many dependencies, keeping 2.11 support should be okay. I had to drop it in my middleware libaries as I found it too hard to find library versions that work across 11, 12 and 13. I will do dependency updates first then (also using your latest release :)) and another library upgrade and when I'm done with that and you haven't come to it, I will try to update this one.

BTW, I found https://github.com/scala/scala-collection-compat/ handy so you can use 
`import scala.jdk.CollectionConverters._` already on 2.12, not sure if you need it.

**Comment by juanpedromoreno** [comment]
This is now part of Fech, thanks @bijancn !
