### ISSUE TITLE
Fetch.run in batches without optimizations

### ISSUE THREAD

**Issue by DenisNovac** [47degrees/fetch#305]
Hi everyone.

I have this piece of code:

```scala
def fetchRandomInt(max: Int) = Fetch(max, randomSource.source)

val fetchTrv: Fetch[IO, List[Int]] = List(10, 10, 10, 10, 10).traverse(fetchRandomInt)

println(Fetch.run(fetchTrv).unsafeRunSync)  // List(7, 7, 7, 7, 7)
```

Where randomSource is just a generator of random ints:

```scala
override def fetch(max: Int): IO[Option[Int]] =
  CF.delay {
    scala.util.Random.nextInt(max).some
  }
```

Is there any way to run this list of commands concurrently in one batch but without optimization by ID?

**Comment by sloshy** [comment]
Hi, obviously this is a late response and I apologize for that. I'm new to the project but I believe I can help you (or future people browsing/arriving from Google) here.

As you may have guessed from the other issue you posted (#306), the Fetch library uses a cache (`DataCache`) with every call to `.run`, with the default cache being a brand new `InMemoryCache`. The behavior of this cache is it effectively deduplicates requests within a single `Fetch` run. The implementation of `.traverse` here means that this cache is shared amongst each request so you see this behavior. If you do not `traverse` or `flatMap` them and instead run them individually, you should see a random number generated each time, as you expect.

**Comment by DenisNovac** [comment]
@sloshy thank you for answer.
